export const OPEN_MODALDIALOG = "OPEN_MODALDIALOG";
export const CLOSE_MODALDIALOG = "CLOSE_MODALDIALOG";
export const SET_MODALDIALOG_HEADER = "SET_MODALDIALOG_HEADER";
export const SET_MODALDIALOG_BODY = "SET_MODALDIALOG_BODY";
export const SET_MODALDIALOG_FOOTER = "SET_MODALDIALOG_FOOTER";

export const SHOW_MODAL = "SHOW_MODAL";
export const HIDE_MODAL = "HIDE_MODAL";
