export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const FETCH_MY_STOCK_SUCCESS = "FETCH_MY_STOCK_SUCCESS";
export const ADD_MY_STOCK_SUCCESS = "ADD_MY_STOCK_SUCCESS";
export const REMOVE_MY_STOCK_SUCCESS = "REMOVE_MY_STOCK_SUCCESS";
